### ISSUE TITLE
py3.6

### ISSUE THREAD

**Issue by CastleDream** [JonathanRaiman/pytreebank#6]
UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 24783: illegal multibyte sequence

**Comment by JonathanRaiman** [comment]
@CastleDream do you know what example that corresponds to in SST? any way to pinpoint what that byte is?

**Comment by feifan-sun** [comment]
This problem recurs in Windows(caused by read `d3.min.js`). The problem can be solved by adding encoding="utf-8" in [this line](https://github.com/JonathanRaiman/pytreebank/blob/master/pytreebank/javascript/__init__.py#L27)
